version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/xenocrm
      - REDIS_URL=redis://redis:6379
      - SESSION_SECRET=your_session_secret
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - mongo
      - redis
    volumes:
      - ./logs:/usr/src/app/logs
      - ./src:/usr/src/app/src
    command: npm run dev

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  mongodb_data:
  redis_data: 