services:
  - type: web
    name: xenocrm-backend
    env: node
    region: oregon
    branch: main
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: COOKIE_DOMAIN
        sync: false
    autoDeploy: true
    plan: free
    disk:
      name: logs
      mountPath: /usr/src/app/logs
      sizeGB: 1

  # Add a cron job for session cleanup
  - type: cron
    name: session-cleanup
    region: oregon
    schedule: "0 */4 * * *"  # Run every 4 hours
    buildCommand: npm install
    startCommand: npm run cleanup-sessions
    envVars:
      - key: NODE_ENV
        value: production
      # Ensure this job has access to the same environment variables as the main service 